services:
  meterrecordingapi:
    image: meterrecordingapi:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  postgreDb:
    image: postgres:13
    environment:
        POSTGRES_USER: local
        POSTGRES_PASSWORD: guess
        POSTGRES_DB: energy_consumption
    volumes:
      - energy_consumption:/var/lib/postgresql/data

volumes:
    energy_consumption:
  